name: 2023 tests

on:
  workflow_dispatch:
  push:
    paths:
      - "src/_2023/**"

env:
  AOC_YEAR: 2023
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests for ${{ env.AOC_YEAR }}
      run: cargo test _${{ env.AOC_YEAR }} --verbose
